export const EMAIL_CHANGED = 'EMAIL_CHANGED';
export const LOGIN_USER_SUCCESSS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAIL = 'LOGIN_USER_FAIL';
export const LOGIN_USER_START = 'LOGIN_USER_START';
