const AUTH0_CLIENT_ID = 'lYR2Wr5R3v9htFSOt0W1RIe7vcUnfX4s';
const AUTH0_DOMAIN = 'trhc-sandbox.auth0.com';
const AUTH0_CLIENT_SECRET = 'z8DzAl_3JezDvp8WKq53x3rF_A9I3gj6XMaJ0pTFND4zdL_ZzU_qwvtYDwCvuFIf'
const NAME = 'WANDER-APP'
export { AUTH0_CLIENT_ID, AUTH0_DOMAIN, AUTH0_CLIENT_SECRET };
